### ISSUE TITLE
Can't enable on PHPBB 3.2

### ISSUE THREAD

**Issue by miri4ever** [david63/david63-userdetails#2]
Can't enable this extension on PHPBB 3.2. It says something like module already exists but I got no extension using any kind of this module called:

Während der Anpassung der Datenbank ist etwas falsch gelaufen und ein Fehler aufgetreten. Die Änderungen, die vor dem Fehler durchgeführt wurden, wurden so weit wie möglich rückgängig gemacht. Du solltest jedoch prüfen, ob dein Board fehlerfrei funktioniert.

Ein Modul existiert bereits: ACP_USER_UTILS

**Comment by david63** [comment]
Please post support questions in the appropriate topic at phpbb.com

Also I do not speak German so I have no idea what most of the above is saying
